//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.07.10 at 05:31:30 PM PDT 
//


package com.google.checkout.schema._2;


/**
 * Java content class for OrderAdjustment complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/home/colinc/projects/apache-tomcat-5.5.12/apiv2.xsd line 337)
 * <p>
 * <pre>
 * &lt;complexType name="OrderAdjustment">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="adjustment-total" type="{http://checkout.google.com/schema/2}Money" minOccurs="0"/>
 *         &lt;element name="merchant-calculation-successful" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="merchant-codes" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;choice maxOccurs="unbounded" minOccurs="0">
 *                     &lt;element name="gift-certificate-adjustment" type="{http://checkout.google.com/schema/2}GiftCertificateAdjustment"/>
 *                     &lt;element name="coupon-adjustment" type="{http://checkout.google.com/schema/2}CouponAdjustment"/>
 *                   &lt;/choice>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="shipping">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="merchant-calculated-shipping-adjustment" type="{http://checkout.google.com/schema/2}MerchantCalculatedShippingAdjustment"/>
 *                   &lt;element name="flat-rate-shipping-adjustment" type="{http://checkout.google.com/schema/2}FlatRateShippingAdjustment"/>
 *                   &lt;element name="pickup-shipping-adjustment" type="{http://checkout.google.com/schema/2}PickupShippingAdjustment"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="total-tax" type="{http://checkout.google.com/schema/2}Money" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface OrderAdjustment {


    /**
     * Gets the value of the merchantCalculationSuccessful property.
     * 
     */
    boolean isMerchantCalculationSuccessful();

    /**
     * Sets the value of the merchantCalculationSuccessful property.
     * 
     */
    void setMerchantCalculationSuccessful(boolean value);

    /**
     * Gets the value of the adjustmentTotal property.
     * 
     * @return
     *     possible object is
     *     {@link com.google.checkout.schema._2.Money}
     */
    com.google.checkout.schema._2.Money getAdjustmentTotal();

    /**
     * Sets the value of the adjustmentTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.google.checkout.schema._2.Money}
     */
    void setAdjustmentTotal(com.google.checkout.schema._2.Money value);

    /**
     * Gets the value of the totalTax property.
     * 
     * @return
     *     possible object is
     *     {@link com.google.checkout.schema._2.Money}
     */
    com.google.checkout.schema._2.Money getTotalTax();

    /**
     * Sets the value of the totalTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.google.checkout.schema._2.Money}
     */
    void setTotalTax(com.google.checkout.schema._2.Money value);

    /**
     * Gets the value of the shipping property.
     * 
     * @return
     *     possible object is
     *     {@link com.google.checkout.schema._2.OrderAdjustment.ShippingType}
     */
    com.google.checkout.schema._2.OrderAdjustment.ShippingType getShipping();

    /**
     * Sets the value of the shipping property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.google.checkout.schema._2.OrderAdjustment.ShippingType}
     */
    void setShipping(com.google.checkout.schema._2.OrderAdjustment.ShippingType value);

    /**
     * Gets the value of the merchantCodes property.
     * 
     * @return
     *     possible object is
     *     {@link com.google.checkout.schema._2.OrderAdjustment.MerchantCodesType}
     */
    com.google.checkout.schema._2.OrderAdjustment.MerchantCodesType getMerchantCodes();

    /**
     * Sets the value of the merchantCodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.google.checkout.schema._2.OrderAdjustment.MerchantCodesType}
     */
    void setMerchantCodes(com.google.checkout.schema._2.OrderAdjustment.MerchantCodesType value);


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/home/colinc/projects/apache-tomcat-5.5.12/apiv2.xsd line 342)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;choice maxOccurs="unbounded" minOccurs="0">
     *           &lt;element name="gift-certificate-adjustment" type="{http://checkout.google.com/schema/2}GiftCertificateAdjustment"/>
     *           &lt;element name="coupon-adjustment" type="{http://checkout.google.com/schema/2}CouponAdjustment"/>
     *         &lt;/choice>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface MerchantCodesType {


        /**
         * Gets the value of the GiftCertificateAdjustmentOrCouponAdjustment property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the GiftCertificateAdjustmentOrCouponAdjustment property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getGiftCertificateAdjustmentOrCouponAdjustment().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link com.google.checkout.schema._2.OrderAdjustment.MerchantCodesType.CouponAdjustment}
         * {@link com.google.checkout.schema._2.OrderAdjustment.MerchantCodesType.GiftCertificateAdjustment}
         * 
         */
        java.util.List getGiftCertificateAdjustmentOrCouponAdjustment();


        /**
         * Java content class for coupon-adjustment element declaration.
         * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/home/colinc/projects/apache-tomcat-5.5.12/apiv2.xsd line 346)
         * <p>
         * <pre>
         * &lt;element name="coupon-adjustment" type="{http://checkout.google.com/schema/2}CouponAdjustment"/>
         * </pre>
         * 
         */
        public interface CouponAdjustment
            extends javax.xml.bind.Element, com.google.checkout.schema._2.CouponAdjustment
        {


        }


        /**
         * Java content class for gift-certificate-adjustment element declaration.
         * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/home/colinc/projects/apache-tomcat-5.5.12/apiv2.xsd line 345)
         * <p>
         * <pre>
         * &lt;element name="gift-certificate-adjustment" type="{http://checkout.google.com/schema/2}GiftCertificateAdjustment"/>
         * </pre>
         * 
         */
        public interface GiftCertificateAdjustment
            extends javax.xml.bind.Element, com.google.checkout.schema._2.GiftCertificateAdjustment
        {


        }

    }


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/home/colinc/projects/apache-tomcat-5.5.12/apiv2.xsd line 352)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="merchant-calculated-shipping-adjustment" type="{http://checkout.google.com/schema/2}MerchantCalculatedShippingAdjustment"/>
     *         &lt;element name="flat-rate-shipping-adjustment" type="{http://checkout.google.com/schema/2}FlatRateShippingAdjustment"/>
     *         &lt;element name="pickup-shipping-adjustment" type="{http://checkout.google.com/schema/2}PickupShippingAdjustment"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface ShippingType {


        /**
         * Gets the value of the merchantCalculatedShippingAdjustment property.
         * 
         * @return
         *     possible object is
         *     {@link com.google.checkout.schema._2.MerchantCalculatedShippingAdjustment}
         */
        com.google.checkout.schema._2.MerchantCalculatedShippingAdjustment getMerchantCalculatedShippingAdjustment();

        /**
         * Sets the value of the merchantCalculatedShippingAdjustment property.
         * 
         * @param value
         *     allowed object is
         *     {@link com.google.checkout.schema._2.MerchantCalculatedShippingAdjustment}
         */
        void setMerchantCalculatedShippingAdjustment(com.google.checkout.schema._2.MerchantCalculatedShippingAdjustment value);

        /**
         * Gets the value of the pickupShippingAdjustment property.
         * 
         * @return
         *     possible object is
         *     {@link com.google.checkout.schema._2.PickupShippingAdjustment}
         */
        com.google.checkout.schema._2.PickupShippingAdjustment getPickupShippingAdjustment();

        /**
         * Sets the value of the pickupShippingAdjustment property.
         * 
         * @param value
         *     allowed object is
         *     {@link com.google.checkout.schema._2.PickupShippingAdjustment}
         */
        void setPickupShippingAdjustment(com.google.checkout.schema._2.PickupShippingAdjustment value);

        /**
         * Gets the value of the flatRateShippingAdjustment property.
         * 
         * @return
         *     possible object is
         *     {@link com.google.checkout.schema._2.FlatRateShippingAdjustment}
         */
        com.google.checkout.schema._2.FlatRateShippingAdjustment getFlatRateShippingAdjustment();

        /**
         * Sets the value of the flatRateShippingAdjustment property.
         * 
         * @param value
         *     allowed object is
         *     {@link com.google.checkout.schema._2.FlatRateShippingAdjustment}
         */
        void setFlatRateShippingAdjustment(com.google.checkout.schema._2.FlatRateShippingAdjustment value);

    }

}
