//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.07.10 at 05:31:30 PM PDT 
//


package com.google.checkout.schema._2;


/**
 * Java content class for ShippingRestrictions complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/home/colinc/projects/apache-tomcat-5.5.12/apiv2.xsd line 135)
 * <p>
 * <pre>
 * &lt;complexType name="ShippingRestrictions">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="allowed-areas">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;choice maxOccurs="unbounded" minOccurs="0">
 *                     &lt;element name="us-state-area" type="{http://checkout.google.com/schema/2}USStateArea"/>
 *                     &lt;element name="us-zip-area" type="{http://checkout.google.com/schema/2}USZipArea"/>
 *                     &lt;element name="us-country-area" type="{http://checkout.google.com/schema/2}USCountryArea"/>
 *                   &lt;/choice>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="excluded-areas" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;choice maxOccurs="unbounded" minOccurs="0">
 *                     &lt;element name="us-state-area" type="{http://checkout.google.com/schema/2}USStateArea"/>
 *                     &lt;element name="us-zip-area" type="{http://checkout.google.com/schema/2}USZipArea"/>
 *                     &lt;element name="us-country-area" type="{http://checkout.google.com/schema/2}USCountryArea"/>
 *                   &lt;/choice>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface ShippingRestrictions {


    /**
     * Gets the value of the allowedAreas property.
     * 
     * @return
     *     possible object is
     *     {@link com.google.checkout.schema._2.ShippingRestrictions.AllowedAreasType}
     */
    com.google.checkout.schema._2.ShippingRestrictions.AllowedAreasType getAllowedAreas();

    /**
     * Sets the value of the allowedAreas property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.google.checkout.schema._2.ShippingRestrictions.AllowedAreasType}
     */
    void setAllowedAreas(com.google.checkout.schema._2.ShippingRestrictions.AllowedAreasType value);

    /**
     * Gets the value of the excludedAreas property.
     * 
     * @return
     *     possible object is
     *     {@link com.google.checkout.schema._2.ShippingRestrictions.ExcludedAreasType}
     */
    com.google.checkout.schema._2.ShippingRestrictions.ExcludedAreasType getExcludedAreas();

    /**
     * Sets the value of the excludedAreas property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.google.checkout.schema._2.ShippingRestrictions.ExcludedAreasType}
     */
    void setExcludedAreas(com.google.checkout.schema._2.ShippingRestrictions.ExcludedAreasType value);


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/home/colinc/projects/apache-tomcat-5.5.12/apiv2.xsd line 138)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;choice maxOccurs="unbounded" minOccurs="0">
     *           &lt;element name="us-state-area" type="{http://checkout.google.com/schema/2}USStateArea"/>
     *           &lt;element name="us-zip-area" type="{http://checkout.google.com/schema/2}USZipArea"/>
     *           &lt;element name="us-country-area" type="{http://checkout.google.com/schema/2}USCountryArea"/>
     *         &lt;/choice>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface AllowedAreasType {


        /**
         * Gets the value of the UsStateAreaOrUsZipAreaOrUsCountryArea property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the UsStateAreaOrUsZipAreaOrUsCountryArea property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getUsStateAreaOrUsZipAreaOrUsCountryArea().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link com.google.checkout.schema._2.ShippingRestrictions.AllowedAreasType.UsCountryArea}
         * {@link com.google.checkout.schema._2.ShippingRestrictions.AllowedAreasType.UsZipArea}
         * {@link com.google.checkout.schema._2.ShippingRestrictions.AllowedAreasType.UsStateArea}
         * 
         */
        java.util.List getUsStateAreaOrUsZipAreaOrUsCountryArea();


        /**
         * Java content class for us-country-area element declaration.
         * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/home/colinc/projects/apache-tomcat-5.5.12/apiv2.xsd line 143)
         * <p>
         * <pre>
         * &lt;element name="us-country-area" type="{http://checkout.google.com/schema/2}USCountryArea"/>
         * </pre>
         * 
         */
        public interface UsCountryArea
            extends javax.xml.bind.Element, com.google.checkout.schema._2.USCountryArea
        {


        }


        /**
         * Java content class for us-state-area element declaration.
         * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/home/colinc/projects/apache-tomcat-5.5.12/apiv2.xsd line 141)
         * <p>
         * <pre>
         * &lt;element name="us-state-area" type="{http://checkout.google.com/schema/2}USStateArea"/>
         * </pre>
         * 
         */
        public interface UsStateArea
            extends javax.xml.bind.Element, com.google.checkout.schema._2.USStateArea
        {


        }


        /**
         * Java content class for us-zip-area element declaration.
         * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/home/colinc/projects/apache-tomcat-5.5.12/apiv2.xsd line 142)
         * <p>
         * <pre>
         * &lt;element name="us-zip-area" type="{http://checkout.google.com/schema/2}USZipArea"/>
         * </pre>
         * 
         */
        public interface UsZipArea
            extends javax.xml.bind.Element, com.google.checkout.schema._2.USZipArea
        {


        }

    }


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/home/colinc/projects/apache-tomcat-5.5.12/apiv2.xsd line 149)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;choice maxOccurs="unbounded" minOccurs="0">
     *           &lt;element name="us-state-area" type="{http://checkout.google.com/schema/2}USStateArea"/>
     *           &lt;element name="us-zip-area" type="{http://checkout.google.com/schema/2}USZipArea"/>
     *           &lt;element name="us-country-area" type="{http://checkout.google.com/schema/2}USCountryArea"/>
     *         &lt;/choice>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface ExcludedAreasType {


        /**
         * Gets the value of the UsStateAreaOrUsZipAreaOrUsCountryArea property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the UsStateAreaOrUsZipAreaOrUsCountryArea property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getUsStateAreaOrUsZipAreaOrUsCountryArea().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link com.google.checkout.schema._2.ShippingRestrictions.ExcludedAreasType.UsCountryArea}
         * {@link com.google.checkout.schema._2.ShippingRestrictions.ExcludedAreasType.UsStateArea}
         * {@link com.google.checkout.schema._2.ShippingRestrictions.ExcludedAreasType.UsZipArea}
         * 
         */
        java.util.List getUsStateAreaOrUsZipAreaOrUsCountryArea();


        /**
         * Java content class for us-country-area element declaration.
         * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/home/colinc/projects/apache-tomcat-5.5.12/apiv2.xsd line 154)
         * <p>
         * <pre>
         * &lt;element name="us-country-area" type="{http://checkout.google.com/schema/2}USCountryArea"/>
         * </pre>
         * 
         */
        public interface UsCountryArea
            extends javax.xml.bind.Element, com.google.checkout.schema._2.USCountryArea
        {


        }


        /**
         * Java content class for us-state-area element declaration.
         * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/home/colinc/projects/apache-tomcat-5.5.12/apiv2.xsd line 152)
         * <p>
         * <pre>
         * &lt;element name="us-state-area" type="{http://checkout.google.com/schema/2}USStateArea"/>
         * </pre>
         * 
         */
        public interface UsStateArea
            extends javax.xml.bind.Element, com.google.checkout.schema._2.USStateArea
        {


        }


        /**
         * Java content class for us-zip-area element declaration.
         * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/home/colinc/projects/apache-tomcat-5.5.12/apiv2.xsd line 153)
         * <p>
         * <pre>
         * &lt;element name="us-zip-area" type="{http://checkout.google.com/schema/2}USZipArea"/>
         * </pre>
         * 
         */
        public interface UsZipArea
            extends javax.xml.bind.Element, com.google.checkout.schema._2.USZipArea
        {


        }

    }

}
