//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.07.10 at 05:31:30 PM PDT 
//


package com.google.checkout.schema._2;


/**
 * Java content class for ShoppingCart complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/home/colinc/projects/apache-tomcat-5.5.12/apiv2.xsd line 71)
 * <p>
 * <pre>
 * &lt;complexType name="ShoppingCart">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="cart-expiration" type="{http://checkout.google.com/schema/2}CartExpiration" minOccurs="0"/>
 *         &lt;element name="items">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="item" type="{http://checkout.google.com/schema/2}Item" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="merchant-private-data" type="{http://checkout.google.com/schema/2}anyType" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface ShoppingCart {


    /**
     * Gets the value of the items property.
     * 
     * @return
     *     possible object is
     *     {@link com.google.checkout.schema._2.ShoppingCart.ItemsType}
     */
    com.google.checkout.schema._2.ShoppingCart.ItemsType getItems();

    /**
     * Sets the value of the items property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.google.checkout.schema._2.ShoppingCart.ItemsType}
     */
    void setItems(com.google.checkout.schema._2.ShoppingCart.ItemsType value);

    /**
     * Gets the value of the cartExpiration property.
     * 
     * @return
     *     possible object is
     *     {@link com.google.checkout.schema._2.CartExpiration}
     */
    com.google.checkout.schema._2.CartExpiration getCartExpiration();

    /**
     * Sets the value of the cartExpiration property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.google.checkout.schema._2.CartExpiration}
     */
    void setCartExpiration(com.google.checkout.schema._2.CartExpiration value);

    /**
     * Gets the value of the merchantPrivateData property.
     * 
     * @return
     *     possible object is
     *     {@link com.google.checkout.schema._2.AnyType}
     */
    com.google.checkout.schema._2.AnyType getMerchantPrivateData();

    /**
     * Sets the value of the merchantPrivateData property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.google.checkout.schema._2.AnyType}
     */
    void setMerchantPrivateData(com.google.checkout.schema._2.AnyType value);


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/home/colinc/projects/apache-tomcat-5.5.12/apiv2.xsd line 75)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="item" type="{http://checkout.google.com/schema/2}Item" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface ItemsType {


        /**
         * Gets the value of the Item property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the Item property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getItem().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link com.google.checkout.schema._2.Item}
         * 
         */
        java.util.List getItem();

    }

}
