//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.07.10 at 05:31:30 PM PDT 
//


package com.google.checkout.schema._2;


/**
 * Java content class for Calculate complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/home/colinc/projects/apache-tomcat-5.5.12/apiv2.xsd line 532)
 * <p>
 * <pre>
 * &lt;complexType name="Calculate">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="addresses" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="anonymous-address" type="{http://checkout.google.com/schema/2}AnonymousAddress" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="merchant-code-strings" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="merchant-code-string" type="{http://checkout.google.com/schema/2}MerchantCodeString" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="shipping" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="method" type="{http://checkout.google.com/schema/2}Method" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="tax" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface Calculate {


    /**
     * Gets the value of the merchantCodeStrings property.
     * 
     * @return
     *     possible object is
     *     {@link com.google.checkout.schema._2.Calculate.MerchantCodeStringsType}
     */
    com.google.checkout.schema._2.Calculate.MerchantCodeStringsType getMerchantCodeStrings();

    /**
     * Sets the value of the merchantCodeStrings property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.google.checkout.schema._2.Calculate.MerchantCodeStringsType}
     */
    void setMerchantCodeStrings(com.google.checkout.schema._2.Calculate.MerchantCodeStringsType value);

    /**
     * Gets the value of the shipping property.
     * 
     * @return
     *     possible object is
     *     {@link com.google.checkout.schema._2.Calculate.ShippingType}
     */
    com.google.checkout.schema._2.Calculate.ShippingType getShipping();

    /**
     * Sets the value of the shipping property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.google.checkout.schema._2.Calculate.ShippingType}
     */
    void setShipping(com.google.checkout.schema._2.Calculate.ShippingType value);

    /**
     * Gets the value of the tax property.
     * 
     */
    boolean isTax();

    /**
     * Sets the value of the tax property.
     * 
     */
    void setTax(boolean value);

    /**
     * Gets the value of the addresses property.
     * 
     * @return
     *     possible object is
     *     {@link com.google.checkout.schema._2.Calculate.AddressesType}
     */
    com.google.checkout.schema._2.Calculate.AddressesType getAddresses();

    /**
     * Sets the value of the addresses property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.google.checkout.schema._2.Calculate.AddressesType}
     */
    void setAddresses(com.google.checkout.schema._2.Calculate.AddressesType value);


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/home/colinc/projects/apache-tomcat-5.5.12/apiv2.xsd line 535)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="anonymous-address" type="{http://checkout.google.com/schema/2}AnonymousAddress" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface AddressesType {


        /**
         * Gets the value of the AnonymousAddress property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the AnonymousAddress property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAnonymousAddress().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link com.google.checkout.schema._2.AnonymousAddress}
         * 
         */
        java.util.List getAnonymousAddress();

    }


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/home/colinc/projects/apache-tomcat-5.5.12/apiv2.xsd line 542)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="merchant-code-string" type="{http://checkout.google.com/schema/2}MerchantCodeString" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface MerchantCodeStringsType {


        /**
         * Gets the value of the MerchantCodeString property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the MerchantCodeString property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMerchantCodeString().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link com.google.checkout.schema._2.MerchantCodeString}
         * 
         */
        java.util.List getMerchantCodeString();

    }


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/home/colinc/projects/apache-tomcat-5.5.12/apiv2.xsd line 549)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="method" type="{http://checkout.google.com/schema/2}Method" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface ShippingType {


        /**
         * Gets the value of the Method property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the Method property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMethod().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link com.google.checkout.schema._2.Method}
         * 
         */
        java.util.List getMethod();

    }

}
