//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.07.10 at 05:31:30 PM PDT 
//


package com.google.checkout.schema._2;


/**
 * Java content class for MerchantCalculations complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/home/colinc/projects/apache-tomcat-5.5.12/apiv2.xsd line 63)
 * <p>
 * <pre>
 * &lt;complexType name="MerchantCalculations">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="accept-gift-certificates" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="accept-merchant-coupons" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="merchant-calculations-url" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface MerchantCalculations {


    /**
     * Gets the value of the merchantCalculationsUrl property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getMerchantCalculationsUrl();

    /**
     * Sets the value of the merchantCalculationsUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setMerchantCalculationsUrl(java.lang.String value);

    /**
     * Gets the value of the acceptMerchantCoupons property.
     * 
     */
    boolean isAcceptMerchantCoupons();

    /**
     * Sets the value of the acceptMerchantCoupons property.
     * 
     */
    void setAcceptMerchantCoupons(boolean value);

    /**
     * Gets the value of the acceptGiftCertificates property.
     * 
     */
    boolean isAcceptGiftCertificates();

    /**
     * Sets the value of the acceptGiftCertificates property.
     * 
     */
    void setAcceptGiftCertificates(boolean value);

}
