//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.07.10 at 05:31:30 PM PDT 
//


package com.google.checkout.schema._2;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.google.checkout.schema._2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
public class ObjectFactory
    extends com.google.checkout.schema._2.impl.runtime.DefaultJAXBContextImpl
{

    private static java.util.HashMap defaultImplementations = new java.util.HashMap(165, 0.75F);
    private static java.util.HashMap rootTagMap = new java.util.HashMap();
    public final static com.google.checkout.schema._2.impl.runtime.GrammarInfo grammarInfo = new com.google.checkout.schema._2.impl.runtime.GrammarInfoImpl(rootTagMap, defaultImplementations, (com.google.checkout.schema._2.ObjectFactory.class));
    public final static java.lang.Class version = (com.google.checkout.schema._2.impl.JAXBVersion.class);

    static {
        defaultImplementations.put((com.google.checkout.schema._2.RefundAmountNotification.class), "com.google.checkout.schema._2.impl.RefundAmountNotificationImpl");
        defaultImplementations.put((com.google.checkout.schema._2.ShippingRestrictions.ExcludedAreasType.UsStateArea.class), "com.google.checkout.schema._2.impl.ShippingRestrictionsImpl.ExcludedAreasTypeImpl.UsStateAreaImpl");
        defaultImplementations.put((com.google.checkout.schema._2.HelloElement.class), "com.google.checkout.schema._2.impl.HelloElementImpl");
        defaultImplementations.put((com.google.checkout.schema._2.RiskInformation.class), "com.google.checkout.schema._2.impl.RiskInformationImpl");
        defaultImplementations.put((com.google.checkout.schema._2.MerchantCalculationResults.ResultsType.class), "com.google.checkout.schema._2.impl.MerchantCalculationResultsImpl.ResultsTypeImpl");
        defaultImplementations.put((com.google.checkout.schema._2.ShippingRestrictions.ExcludedAreasType.UsZipArea.class), "com.google.checkout.schema._2.impl.ShippingRestrictionsImpl.ExcludedAreasTypeImpl.UsZipAreaImpl");
        defaultImplementations.put((com.google.checkout.schema._2.AlternateTaxRule.class), "com.google.checkout.schema._2.impl.AlternateTaxRuleImpl");
        defaultImplementations.put((com.google.checkout.schema._2.AlternateTaxTable.class), "com.google.checkout.schema._2.impl.AlternateTaxTableImpl");
        defaultImplementations.put((com.google.checkout.schema._2.ChargeAmountNotificationElement.class), "com.google.checkout.schema._2.impl.ChargeAmountNotificationElementImpl");
        defaultImplementations.put((com.google.checkout.schema._2.MerchantCalculationResultsElement.class), "com.google.checkout.schema._2.impl.MerchantCalculationResultsElementImpl");
        defaultImplementations.put((com.google.checkout.schema._2.RiskInformationNotification.class), "com.google.checkout.schema._2.impl.RiskInformationNotificationImpl");
        defaultImplementations.put((com.google.checkout.schema._2.ChargeAmountNotification.class), "com.google.checkout.schema._2.impl.ChargeAmountNotificationImpl");
        defaultImplementations.put((com.google.checkout.schema._2.NewOrderNotification.class), "com.google.checkout.schema._2.impl.NewOrderNotificationImpl");
        defaultImplementations.put((com.google.checkout.schema._2.SendBuyerMessageElement.class), "com.google.checkout.schema._2.impl.SendBuyerMessageElementImpl");
        defaultImplementations.put((com.google.checkout.schema._2.GiftCertificateAdjustment.class), "com.google.checkout.schema._2.impl.GiftCertificateAdjustmentImpl");
        defaultImplementations.put((com.google.checkout.schema._2.USCountryArea.class), "com.google.checkout.schema._2.impl.USCountryAreaImpl");
        defaultImplementations.put((com.google.checkout.schema._2.ErrorElement.class), "com.google.checkout.schema._2.impl.ErrorElementImpl");
        defaultImplementations.put((com.google.checkout.schema._2.CheckoutShoppingCart.CheckoutFlowSupportType.class), "com.google.checkout.schema._2.impl.CheckoutShoppingCartImpl.CheckoutFlowSupportTypeImpl");
        defaultImplementations.put((com.google.checkout.schema._2.FlatRateShipping.class), "com.google.checkout.schema._2.impl.FlatRateShippingImpl");
        defaultImplementations.put((com.google.checkout.schema._2.MerchantCheckoutFlowSupport.ShippingMethodsType.class), "com.google.checkout.schema._2.impl.MerchantCheckoutFlowSupportImpl.ShippingMethodsTypeImpl");
        defaultImplementations.put((com.google.checkout.schema._2.MerchantCheckoutFlowSupport.class), "com.google.checkout.schema._2.impl.MerchantCheckoutFlowSupportImpl");
        defaultImplementations.put((com.google.checkout.schema._2.ChargebackAmountNotification.class), "com.google.checkout.schema._2.impl.ChargebackAmountNotificationImpl");
        defaultImplementations.put((com.google.checkout.schema._2.DefaultTaxRule.TaxAreaType.class), "com.google.checkout.schema._2.impl.DefaultTaxRuleImpl.TaxAreaTypeImpl");
        defaultImplementations.put((com.google.checkout.schema._2.CancelOrderElement.class), "com.google.checkout.schema._2.impl.CancelOrderElementImpl");
        defaultImplementations.put((com.google.checkout.schema._2.Item.class), "com.google.checkout.schema._2.impl.ItemImpl");
        defaultImplementations.put((com.google.checkout.schema._2.ChargebackAmountNotificationElement.class), "com.google.checkout.schema._2.impl.ChargebackAmountNotificationElementImpl");
        defaultImplementations.put((com.google.checkout.schema._2.OrderAdjustment.ShippingType.class), "com.google.checkout.schema._2.impl.OrderAdjustmentImpl.ShippingTypeImpl");
        defaultImplementations.put((com.google.checkout.schema._2.AddTrackingDataRequest.class), "com.google.checkout.schema._2.impl.AddTrackingDataRequestImpl");
        defaultImplementations.put((com.google.checkout.schema._2.RequestReceivedElement.class), "com.google.checkout.schema._2.impl.RequestReceivedElementImpl");
        defaultImplementations.put((com.google.checkout.schema._2.TaxTables.class), "com.google.checkout.schema._2.impl.TaxTablesImpl");
        defaultImplementations.put((com.google.checkout.schema._2.CheckoutRedirectElement.class), "com.google.checkout.schema._2.impl.CheckoutRedirectElementImpl");
        defaultImplementations.put((com.google.checkout.schema._2.DiagnosisElement.class), "com.google.checkout.schema._2.impl.DiagnosisElementImpl");
        defaultImplementations.put((com.google.checkout.schema._2.Result.MerchantCodeResultsType.GiftCertificateResult.class), "com.google.checkout.schema._2.impl.ResultImpl.MerchantCodeResultsTypeImpl.GiftCertificateResultImpl");
        defaultImplementations.put((com.google.checkout.schema._2.OrderStateChangeNotificationElement.class), "com.google.checkout.schema._2.impl.OrderStateChangeNotificationElementImpl");
        defaultImplementations.put((com.google.checkout.schema._2.ProcessOrderElement.class), "com.google.checkout.schema._2.impl.ProcessOrderElementImpl");
        defaultImplementations.put((com.google.checkout.schema._2.OrderAdjustment.class), "com.google.checkout.schema._2.impl.OrderAdjustmentImpl");
        defaultImplementations.put((com.google.checkout.schema._2.Money.class), "com.google.checkout.schema._2.impl.MoneyImpl");
        defaultImplementations.put((com.google.checkout.schema._2.Result.MerchantCodeResultsType.CouponResult.class), "com.google.checkout.schema._2.impl.ResultImpl.MerchantCodeResultsTypeImpl.CouponResultImpl");
        defaultImplementations.put((com.google.checkout.schema._2.AddMerchantOrderNumberElement.class), "com.google.checkout.schema._2.impl.AddMerchantOrderNumberElementImpl");
        defaultImplementations.put((com.google.checkout.schema._2.AddTrackingDataElement.class), "com.google.checkout.schema._2.impl.AddTrackingDataElementImpl");
        defaultImplementations.put((com.google.checkout.schema._2.DefaultTaxTable.class), "com.google.checkout.schema._2.impl.DefaultTaxTableImpl");
        defaultImplementations.put((com.google.checkout.schema._2.Calculate.class), "com.google.checkout.schema._2.impl.CalculateImpl");
        defaultImplementations.put((com.google.checkout.schema._2.NotificationAcknowledgment.class), "com.google.checkout.schema._2.impl.NotificationAcknowledgmentImpl");
        defaultImplementations.put((com.google.checkout.schema._2.NotificationAcknowledgmentElement.class), "com.google.checkout.schema._2.impl.NotificationAcknowledgmentElementImpl");
        defaultImplementations.put((com.google.checkout.schema._2.BuyerMarketingPreferencesElement.class), "com.google.checkout.schema._2.impl.BuyerMarketingPreferencesElementImpl");
        defaultImplementations.put((com.google.checkout.schema._2.MerchantCheckoutFlowSupport.ShippingMethodsType.FlatRateShipping.class), "com.google.checkout.schema._2.impl.MerchantCheckoutFlowSupportImpl.ShippingMethodsTypeImpl.FlatRateShippingImpl");
        defaultImplementations.put((com.google.checkout.schema._2.UnarchiveOrderElement.class), "com.google.checkout.schema._2.impl.UnarchiveOrderElementImpl");
        defaultImplementations.put((com.google.checkout.schema._2.ChargeOrderRequest.class), "com.google.checkout.schema._2.impl.ChargeOrderRequestImpl");
        defaultImplementations.put((com.google.checkout.schema._2.AlternateTaxRule.TaxAreaType.class), "com.google.checkout.schema._2.impl.AlternateTaxRuleImpl.TaxAreaTypeImpl");
        defaultImplementations.put((com.google.checkout.schema._2.Hello.class), "com.google.checkout.schema._2.impl.HelloImpl");
        defaultImplementations.put((com.google.checkout.schema._2.DemoFailureElement.class), "com.google.checkout.schema._2.impl.DemoFailureElementImpl");
        defaultImplementations.put((com.google.checkout.schema._2.ShippingRestrictions.AllowedAreasType.UsCountryArea.class), "com.google.checkout.schema._2.impl.ShippingRestrictionsImpl.AllowedAreasTypeImpl.UsCountryAreaImpl");
        defaultImplementations.put((com.google.checkout.schema._2.ArchiveOrderElement.class), "com.google.checkout.schema._2.impl.ArchiveOrderElementImpl");
        defaultImplementations.put((com.google.checkout.schema._2.CheckoutRedirect.class), "com.google.checkout.schema._2.impl.CheckoutRedirectImpl");
        defaultImplementations.put((com.google.checkout.schema._2.AnonymousAddress.class), "com.google.checkout.schema._2.impl.AnonymousAddressImpl");
        defaultImplementations.put((com.google.checkout.schema._2.CancelOrderRequest.class), "com.google.checkout.schema._2.impl.CancelOrderRequestImpl");
        defaultImplementations.put((com.google.checkout.schema._2.GiftCertificateResult.class), "com.google.checkout.schema._2.impl.GiftCertificateResultImpl");
        defaultImplementations.put((com.google.checkout.schema._2.NewOrderNotificationElement.class), "com.google.checkout.schema._2.impl.NewOrderNotificationElementImpl");
        defaultImplementations.put((com.google.checkout.schema._2.MerchantCalculationCallback.class), "com.google.checkout.schema._2.impl.MerchantCalculationCallbackImpl");
        defaultImplementations.put((com.google.checkout.schema._2.Method.class), "com.google.checkout.schema._2.impl.MethodImpl");
        defaultImplementations.put((com.google.checkout.schema._2.OrderAdjustment.MerchantCodesType.CouponAdjustment.class), "com.google.checkout.schema._2.impl.OrderAdjustmentImpl.MerchantCodesTypeImpl.CouponAdjustmentImpl");
        defaultImplementations.put((com.google.checkout.schema._2.ShippingRestrictions.ExcludedAreasType.UsCountryArea.class), "com.google.checkout.schema._2.impl.ShippingRestrictionsImpl.ExcludedAreasTypeImpl.UsCountryAreaImpl");
        defaultImplementations.put((com.google.checkout.schema._2.MerchantCheckoutFlowSupport.ShippingMethodsType.Pickup.class), "com.google.checkout.schema._2.impl.MerchantCheckoutFlowSupportImpl.ShippingMethodsTypeImpl.PickupImpl");
        defaultImplementations.put((com.google.checkout.schema._2.Calculate.MerchantCodeStringsType.class), "com.google.checkout.schema._2.impl.CalculateImpl.MerchantCodeStringsTypeImpl");
        defaultImplementations.put((com.google.checkout.schema._2.MerchantCalculatedShippingAdjustment.class), "com.google.checkout.schema._2.impl.MerchantCalculatedShippingAdjustmentImpl");
        defaultImplementations.put((com.google.checkout.schema._2.Address.class), "com.google.checkout.schema._2.impl.AddressImpl");
        defaultImplementations.put((com.google.checkout.schema._2.Result.class), "com.google.checkout.schema._2.impl.ResultImpl");
        defaultImplementations.put((com.google.checkout.schema._2.Calculate.AddressesType.class), "com.google.checkout.schema._2.impl.CalculateImpl.AddressesTypeImpl");
        defaultImplementations.put((com.google.checkout.schema._2.ArchiveOrderRequest.class), "com.google.checkout.schema._2.impl.ArchiveOrderRequestImpl");
        defaultImplementations.put((com.google.checkout.schema._2.MerchantCalculationResults.class), "com.google.checkout.schema._2.impl.MerchantCalculationResultsImpl");
        defaultImplementations.put((com.google.checkout.schema._2.RefundOrderRequest.class), "com.google.checkout.schema._2.impl.RefundOrderRequestImpl");
        defaultImplementations.put((com.google.checkout.schema._2.ShoppingCart.ItemsType.class), "com.google.checkout.schema._2.impl.ShoppingCartImpl.ItemsTypeImpl");
        defaultImplementations.put((com.google.checkout.schema._2.ShippingRestrictions.AllowedAreasType.UsStateArea.class), "com.google.checkout.schema._2.impl.ShippingRestrictionsImpl.AllowedAreasTypeImpl.UsStateAreaImpl");
        defaultImplementations.put((com.google.checkout.schema._2.RefundAmountNotificationElement.class), "com.google.checkout.schema._2.impl.RefundAmountNotificationElementImpl");
        defaultImplementations.put((com.google.checkout.schema._2.CouponResult.class), "com.google.checkout.schema._2.impl.CouponResultImpl");
        defaultImplementations.put((com.google.checkout.schema._2.DiagnoseResponse.class), "com.google.checkout.schema._2.impl.DiagnoseResponseImpl");
        defaultImplementations.put((com.google.checkout.schema._2.MerchantCodeString.class), "com.google.checkout.schema._2.impl.MerchantCodeStringImpl");
        defaultImplementations.put((com.google.checkout.schema._2.FlatRateShippingAdjustment.class), "com.google.checkout.schema._2.impl.FlatRateShippingAdjustmentImpl");
        defaultImplementations.put((com.google.checkout.schema._2.Result.MerchantCodeResultsType.class), "com.google.checkout.schema._2.impl.ResultImpl.MerchantCodeResultsTypeImpl");
        defaultImplementations.put((com.google.checkout.schema._2.ChargeOrderElement.class), "com.google.checkout.schema._2.impl.ChargeOrderElementImpl");
        defaultImplementations.put((com.google.checkout.schema._2.ShippingRestrictions.ExcludedAreasType.class), "com.google.checkout.schema._2.impl.ShippingRestrictionsImpl.ExcludedAreasTypeImpl");
        defaultImplementations.put((com.google.checkout.schema._2.SendBuyerMessageRequest.class), "com.google.checkout.schema._2.impl.SendBuyerMessageRequestImpl");
        defaultImplementations.put((com.google.checkout.schema._2.ProcessOrderRequest.class), "com.google.checkout.schema._2.impl.ProcessOrderRequestImpl");
        defaultImplementations.put((com.google.checkout.schema._2.UnarchiveOrderRequest.class), "com.google.checkout.schema._2.impl.UnarchiveOrderRequestImpl");
        defaultImplementations.put((com.google.checkout.schema._2.MerchantCheckoutFlowSupport.ShippingMethodsType.MerchantCalculatedShipping.class), "com.google.checkout.schema._2.impl.MerchantCheckoutFlowSupportImpl.ShippingMethodsTypeImpl.MerchantCalculatedShippingImpl");
        defaultImplementations.put((com.google.checkout.schema._2.ShoppingCart.class), "com.google.checkout.schema._2.impl.ShoppingCartImpl");
        defaultImplementations.put((com.google.checkout.schema._2.RequestReceivedResponse.class), "com.google.checkout.schema._2.impl.RequestReceivedResponseImpl");
        defaultImplementations.put((com.google.checkout.schema._2.ByeElement.class), "com.google.checkout.schema._2.impl.ByeElementImpl");
        defaultImplementations.put((com.google.checkout.schema._2.ShippingRestrictions.class), "com.google.checkout.schema._2.impl.ShippingRestrictionsImpl");
        defaultImplementations.put((com.google.checkout.schema._2.ShippingRestrictions.AllowedAreasType.UsZipArea.class), "com.google.checkout.schema._2.impl.ShippingRestrictionsImpl.AllowedAreasTypeImpl.UsZipAreaImpl");
        defaultImplementations.put((com.google.checkout.schema._2.OrderStateChangeNotification.class), "com.google.checkout.schema._2.impl.OrderStateChangeNotificationImpl");
        defaultImplementations.put((com.google.checkout.schema._2.USStateArea.class), "com.google.checkout.schema._2.impl.USStateAreaImpl");
        defaultImplementations.put((com.google.checkout.schema._2.MerchantCalculations.class), "com.google.checkout.schema._2.impl.MerchantCalculationsImpl");
        defaultImplementations.put((com.google.checkout.schema._2.RefundOrderElement.class), "com.google.checkout.schema._2.impl.RefundOrderElementImpl");
        defaultImplementations.put((com.google.checkout.schema._2.AddMerchantOrderNumberRequest.class), "com.google.checkout.schema._2.impl.AddMerchantOrderNumberRequestImpl");
        defaultImplementations.put((com.google.checkout.schema._2.DeliverOrderRequest.class), "com.google.checkout.schema._2.impl.DeliverOrderRequestImpl");
        defaultImplementations.put((com.google.checkout.schema._2.Bye.class), "com.google.checkout.schema._2.impl.ByeImpl");
        defaultImplementations.put((com.google.checkout.schema._2.ErrorResponse.WarningMessagesType.class), "com.google.checkout.schema._2.impl.ErrorResponseImpl.WarningMessagesTypeImpl");
        defaultImplementations.put((com.google.checkout.schema._2.OrderAdjustment.MerchantCodesType.GiftCertificateAdjustment.class), "com.google.checkout.schema._2.impl.OrderAdjustmentImpl.MerchantCodesTypeImpl.GiftCertificateAdjustmentImpl");
        defaultImplementations.put((com.google.checkout.schema._2.CheckoutShoppingCart.class), "com.google.checkout.schema._2.impl.CheckoutShoppingCartImpl");
        defaultImplementations.put((com.google.checkout.schema._2.ShippingRestrictions.AllowedAreasType.class), "com.google.checkout.schema._2.impl.ShippingRestrictionsImpl.AllowedAreasTypeImpl");
        defaultImplementations.put((com.google.checkout.schema._2.ErrorResponse.class), "com.google.checkout.schema._2.impl.ErrorResponseImpl");
        defaultImplementations.put((com.google.checkout.schema._2.TaxTables.AlternateTaxTablesType.class), "com.google.checkout.schema._2.impl.TaxTablesImpl.AlternateTaxTablesTypeImpl");
        defaultImplementations.put((com.google.checkout.schema._2.PickupShippingAdjustment.class), "com.google.checkout.schema._2.impl.PickupShippingAdjustmentImpl");
        defaultImplementations.put((com.google.checkout.schema._2.DefaultTaxRule.class), "com.google.checkout.schema._2.impl.DefaultTaxRuleImpl");
        defaultImplementations.put((com.google.checkout.schema._2.MerchantCalculatedShipping.class), "com.google.checkout.schema._2.impl.MerchantCalculatedShippingImpl");
        defaultImplementations.put((com.google.checkout.schema._2.OrderAdjustment.MerchantCodesType.class), "com.google.checkout.schema._2.impl.OrderAdjustmentImpl.MerchantCodesTypeImpl");
        defaultImplementations.put((com.google.checkout.schema._2.USZipArea.class), "com.google.checkout.schema._2.impl.USZipAreaImpl");
        defaultImplementations.put((com.google.checkout.schema._2.TrackingData.class), "com.google.checkout.schema._2.impl.TrackingDataImpl");
        defaultImplementations.put((com.google.checkout.schema._2.CartExpiration.class), "com.google.checkout.schema._2.impl.CartExpirationImpl");
        defaultImplementations.put((com.google.checkout.schema._2.AnyType.class), "com.google.checkout.schema._2.impl.AnyTypeImpl");
        defaultImplementations.put((com.google.checkout.schema._2.DiagnoseResponse.WarningsType.class), "com.google.checkout.schema._2.impl.DiagnoseResponseImpl.WarningsTypeImpl");
        defaultImplementations.put((com.google.checkout.schema._2.Pickup.class), "com.google.checkout.schema._2.impl.PickupImpl");
        defaultImplementations.put((com.google.checkout.schema._2.Calculate.ShippingType.class), "com.google.checkout.schema._2.impl.CalculateImpl.ShippingTypeImpl");
        defaultImplementations.put((com.google.checkout.schema._2.CheckoutShoppingCartElement.class), "com.google.checkout.schema._2.impl.CheckoutShoppingCartElementImpl");
        defaultImplementations.put((com.google.checkout.schema._2.DefaultTaxTable.TaxRulesType.class), "com.google.checkout.schema._2.impl.DefaultTaxTableImpl.TaxRulesTypeImpl");
        defaultImplementations.put((com.google.checkout.schema._2.BuyerMarketingPreferences.class), "com.google.checkout.schema._2.impl.BuyerMarketingPreferencesImpl");
        defaultImplementations.put((com.google.checkout.schema._2.DemoFailure.class), "com.google.checkout.schema._2.impl.DemoFailureImpl");
        defaultImplementations.put((com.google.checkout.schema._2.CouponAdjustment.class), "com.google.checkout.schema._2.impl.CouponAdjustmentImpl");
        defaultImplementations.put((com.google.checkout.schema._2.DeliverOrderElement.class), "com.google.checkout.schema._2.impl.DeliverOrderElementImpl");
        defaultImplementations.put((com.google.checkout.schema._2.MerchantCalculationCallbackElement.class), "com.google.checkout.schema._2.impl.MerchantCalculationCallbackElementImpl");
        defaultImplementations.put((com.google.checkout.schema._2.AlternateTaxTable.AlternateTaxRulesType.class), "com.google.checkout.schema._2.impl.AlternateTaxTableImpl.AlternateTaxRulesTypeImpl");
        defaultImplementations.put((com.google.checkout.schema._2.RiskInformationNotificationElement.class), "com.google.checkout.schema._2.impl.RiskInformationNotificationElementImpl");
        rootTagMap.put(new javax.xml.namespace.QName("http://checkout.google.com/schema/2", "request-received"), (com.google.checkout.schema._2.RequestReceivedElement.class));
        rootTagMap.put(new javax.xml.namespace.QName("http://checkout.google.com/schema/2", "chargeback-amount-notification"), (com.google.checkout.schema._2.ChargebackAmountNotificationElement.class));
        rootTagMap.put(new javax.xml.namespace.QName("http://checkout.google.com/schema/2", "refund-order"), (com.google.checkout.schema._2.RefundOrderElement.class));
        rootTagMap.put(new javax.xml.namespace.QName("http://checkout.google.com/schema/2", "notification-acknowledgment"), (com.google.checkout.schema._2.NotificationAcknowledgmentElement.class));
        rootTagMap.put(new javax.xml.namespace.QName("http://checkout.google.com/schema/2", "archive-order"), (com.google.checkout.schema._2.ArchiveOrderElement.class));
        rootTagMap.put(new javax.xml.namespace.QName("http://checkout.google.com/schema/2", "unarchive-order"), (com.google.checkout.schema._2.UnarchiveOrderElement.class));
        rootTagMap.put(new javax.xml.namespace.QName("http://checkout.google.com/schema/2", "bye"), (com.google.checkout.schema._2.ByeElement.class));
        rootTagMap.put(new javax.xml.namespace.QName("http://checkout.google.com/schema/2", "merchant-calculation-callback"), (com.google.checkout.schema._2.MerchantCalculationCallbackElement.class));
        rootTagMap.put(new javax.xml.namespace.QName("http://checkout.google.com/schema/2", "process-order"), (com.google.checkout.schema._2.ProcessOrderElement.class));
        rootTagMap.put(new javax.xml.namespace.QName("http://checkout.google.com/schema/2", "new-order-notification"), (com.google.checkout.schema._2.NewOrderNotificationElement.class));
        rootTagMap.put(new javax.xml.namespace.QName("http://checkout.google.com/schema/2", "checkout-redirect"), (com.google.checkout.schema._2.CheckoutRedirectElement.class));
        rootTagMap.put(new javax.xml.namespace.QName("http://checkout.google.com/schema/2", "send-buyer-message"), (com.google.checkout.schema._2.SendBuyerMessageElement.class));
        rootTagMap.put(new javax.xml.namespace.QName("http://checkout.google.com/schema/2", "charge-order"), (com.google.checkout.schema._2.ChargeOrderElement.class));
        rootTagMap.put(new javax.xml.namespace.QName("http://checkout.google.com/schema/2", "refund-amount-notification"), (com.google.checkout.schema._2.RefundAmountNotificationElement.class));
        rootTagMap.put(new javax.xml.namespace.QName("http://checkout.google.com/schema/2", "hello"), (com.google.checkout.schema._2.HelloElement.class));
        rootTagMap.put(new javax.xml.namespace.QName("http://checkout.google.com/schema/2", "charge-amount-notification"), (com.google.checkout.schema._2.ChargeAmountNotificationElement.class));
        rootTagMap.put(new javax.xml.namespace.QName("http://checkout.google.com/schema/2", "deliver-order"), (com.google.checkout.schema._2.DeliverOrderElement.class));
        rootTagMap.put(new javax.xml.namespace.QName("http://checkout.google.com/schema/2", "merchant-calculation-results"), (com.google.checkout.schema._2.MerchantCalculationResultsElement.class));
        rootTagMap.put(new javax.xml.namespace.QName("http://checkout.google.com/schema/2", "add-tracking-data"), (com.google.checkout.schema._2.AddTrackingDataElement.class));
        rootTagMap.put(new javax.xml.namespace.QName("http://checkout.google.com/schema/2", "buyer-marketing-preferences"), (com.google.checkout.schema._2.BuyerMarketingPreferencesElement.class));
        rootTagMap.put(new javax.xml.namespace.QName("http://checkout.google.com/schema/2", "error"), (com.google.checkout.schema._2.ErrorElement.class));
        rootTagMap.put(new javax.xml.namespace.QName("http://checkout.google.com/schema/2", "checkout-shopping-cart"), (com.google.checkout.schema._2.CheckoutShoppingCartElement.class));
        rootTagMap.put(new javax.xml.namespace.QName("http://checkout.google.com/schema/2", "cancel-order"), (com.google.checkout.schema._2.CancelOrderElement.class));
        rootTagMap.put(new javax.xml.namespace.QName("http://checkout.google.com/schema/2", "add-merchant-order-number"), (com.google.checkout.schema._2.AddMerchantOrderNumberElement.class));
        rootTagMap.put(new javax.xml.namespace.QName("http://checkout.google.com/schema/2", "demo-failure"), (com.google.checkout.schema._2.DemoFailureElement.class));
        rootTagMap.put(new javax.xml.namespace.QName("http://checkout.google.com/schema/2", "diagnosis"), (com.google.checkout.schema._2.DiagnosisElement.class));
        rootTagMap.put(new javax.xml.namespace.QName("http://checkout.google.com/schema/2", "risk-information-notification"), (com.google.checkout.schema._2.RiskInformationNotificationElement.class));
        rootTagMap.put(new javax.xml.namespace.QName("http://checkout.google.com/schema/2", "order-state-change-notification"), (com.google.checkout.schema._2.OrderStateChangeNotificationElement.class));
    }

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.google.checkout.schema._2
     * 
     */
    public ObjectFactory() {
        super(grammarInfo);
    }

    /**
     * Create an instance of the specified Java content interface.
     * 
     * @param javaContentInterface
     *     the Class object of the javacontent interface to instantiate
     * @return
     *     a new instance
     * @throws JAXBException
     *     if an error occurs
     */
    public java.lang.Object newInstance(java.lang.Class javaContentInterface)
        throws javax.xml.bind.JAXBException
    {
        return super.newInstance(javaContentInterface);
    }

    /**
     * Get the specified property. This method can only be
     * used to get provider specific properties.
     * Attempting to get an undefined property will result
     * in a PropertyException being thrown.
     * 
     * @param name
     *     the name of the property to retrieve
     * @return
     *     the value of the requested property
     * @throws PropertyException
     *     when there is an error retrieving the given property or value
     */
    public java.lang.Object getProperty(java.lang.String name)
        throws javax.xml.bind.PropertyException
    {
        return super.getProperty(name);
    }

    /**
     * Set the specified property. This method can only be
     * used to set provider specific properties.
     * Attempting to set an undefined property will result
     * in a PropertyException being thrown.
     * 
     * @param value
     *     the value of the property to be set
     * @param name
     *     the name of the property to retrieve
     * @throws PropertyException
     *     when there is an error processing the given property or value
     */
    public void setProperty(java.lang.String name, java.lang.Object value)
        throws javax.xml.bind.PropertyException
    {
        super.setProperty(name, value);
    }

    /**
     * Create an instance of RefundAmountNotification
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.RefundAmountNotification createRefundAmountNotification()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.RefundAmountNotificationImpl();
    }

    /**
     * Create an instance of ShippingRestrictionsExcludedAreasTypeUsStateArea
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.ShippingRestrictions.ExcludedAreasType.UsStateArea createShippingRestrictionsExcludedAreasTypeUsStateArea()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.ShippingRestrictionsImpl.ExcludedAreasTypeImpl.UsStateAreaImpl();
    }

    /**
     * Create an instance of HelloElement
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.HelloElement createHelloElement()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.HelloElementImpl();
    }

    /**
     * Create an instance of RiskInformation
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.RiskInformation createRiskInformation()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.RiskInformationImpl();
    }

    /**
     * Create an instance of MerchantCalculationResultsResultsType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.MerchantCalculationResults.ResultsType createMerchantCalculationResultsResultsType()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.MerchantCalculationResultsImpl.ResultsTypeImpl();
    }

    /**
     * Create an instance of ShippingRestrictionsExcludedAreasTypeUsZipArea
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.ShippingRestrictions.ExcludedAreasType.UsZipArea createShippingRestrictionsExcludedAreasTypeUsZipArea()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.ShippingRestrictionsImpl.ExcludedAreasTypeImpl.UsZipAreaImpl();
    }

    /**
     * Create an instance of AlternateTaxRule
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.AlternateTaxRule createAlternateTaxRule()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.AlternateTaxRuleImpl();
    }

    /**
     * Create an instance of AlternateTaxTable
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.AlternateTaxTable createAlternateTaxTable()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.AlternateTaxTableImpl();
    }

    /**
     * Create an instance of ChargeAmountNotificationElement
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.ChargeAmountNotificationElement createChargeAmountNotificationElement()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.ChargeAmountNotificationElementImpl();
    }

    /**
     * Create an instance of MerchantCalculationResultsElement
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.MerchantCalculationResultsElement createMerchantCalculationResultsElement()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.MerchantCalculationResultsElementImpl();
    }

    /**
     * Create an instance of RiskInformationNotification
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.RiskInformationNotification createRiskInformationNotification()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.RiskInformationNotificationImpl();
    }

    /**
     * Create an instance of ChargeAmountNotification
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.ChargeAmountNotification createChargeAmountNotification()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.ChargeAmountNotificationImpl();
    }

    /**
     * Create an instance of NewOrderNotification
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.NewOrderNotification createNewOrderNotification()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.NewOrderNotificationImpl();
    }

    /**
     * Create an instance of SendBuyerMessageElement
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.SendBuyerMessageElement createSendBuyerMessageElement()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.SendBuyerMessageElementImpl();
    }

    /**
     * Create an instance of GiftCertificateAdjustment
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.GiftCertificateAdjustment createGiftCertificateAdjustment()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.GiftCertificateAdjustmentImpl();
    }

    /**
     * Create an instance of USCountryArea
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.USCountryArea createUSCountryArea()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.USCountryAreaImpl();
    }

    /**
     * Create an instance of ErrorElement
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.ErrorElement createErrorElement()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.ErrorElementImpl();
    }

    /**
     * Create an instance of CheckoutShoppingCartCheckoutFlowSupportType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.CheckoutShoppingCart.CheckoutFlowSupportType createCheckoutShoppingCartCheckoutFlowSupportType()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.CheckoutShoppingCartImpl.CheckoutFlowSupportTypeImpl();
    }

    /**
     * Create an instance of FlatRateShipping
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.FlatRateShipping createFlatRateShipping()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.FlatRateShippingImpl();
    }

    /**
     * Create an instance of MerchantCheckoutFlowSupportShippingMethodsType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.MerchantCheckoutFlowSupport.ShippingMethodsType createMerchantCheckoutFlowSupportShippingMethodsType()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.MerchantCheckoutFlowSupportImpl.ShippingMethodsTypeImpl();
    }

    /**
     * Create an instance of MerchantCheckoutFlowSupport
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.MerchantCheckoutFlowSupport createMerchantCheckoutFlowSupport()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.MerchantCheckoutFlowSupportImpl();
    }

    /**
     * Create an instance of ChargebackAmountNotification
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.ChargebackAmountNotification createChargebackAmountNotification()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.ChargebackAmountNotificationImpl();
    }

    /**
     * Create an instance of DefaultTaxRuleTaxAreaType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.DefaultTaxRule.TaxAreaType createDefaultTaxRuleTaxAreaType()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.DefaultTaxRuleImpl.TaxAreaTypeImpl();
    }

    /**
     * Create an instance of CancelOrderElement
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.CancelOrderElement createCancelOrderElement()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.CancelOrderElementImpl();
    }

    /**
     * Create an instance of Item
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.Item createItem()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.ItemImpl();
    }

    /**
     * Create an instance of ChargebackAmountNotificationElement
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.ChargebackAmountNotificationElement createChargebackAmountNotificationElement()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.ChargebackAmountNotificationElementImpl();
    }

    /**
     * Create an instance of OrderAdjustmentShippingType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.OrderAdjustment.ShippingType createOrderAdjustmentShippingType()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.OrderAdjustmentImpl.ShippingTypeImpl();
    }

    /**
     * Create an instance of AddTrackingDataRequest
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.AddTrackingDataRequest createAddTrackingDataRequest()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.AddTrackingDataRequestImpl();
    }

    /**
     * Create an instance of RequestReceivedElement
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.RequestReceivedElement createRequestReceivedElement()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.RequestReceivedElementImpl();
    }

    /**
     * Create an instance of TaxTables
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.TaxTables createTaxTables()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.TaxTablesImpl();
    }

    /**
     * Create an instance of CheckoutRedirectElement
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.CheckoutRedirectElement createCheckoutRedirectElement()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.CheckoutRedirectElementImpl();
    }

    /**
     * Create an instance of DiagnosisElement
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.DiagnosisElement createDiagnosisElement()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.DiagnosisElementImpl();
    }

    /**
     * Create an instance of ResultMerchantCodeResultsTypeGiftCertificateResult
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.Result.MerchantCodeResultsType.GiftCertificateResult createResultMerchantCodeResultsTypeGiftCertificateResult()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.ResultImpl.MerchantCodeResultsTypeImpl.GiftCertificateResultImpl();
    }

    /**
     * Create an instance of OrderStateChangeNotificationElement
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.OrderStateChangeNotificationElement createOrderStateChangeNotificationElement()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.OrderStateChangeNotificationElementImpl();
    }

    /**
     * Create an instance of ProcessOrderElement
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.ProcessOrderElement createProcessOrderElement()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.ProcessOrderElementImpl();
    }

    /**
     * Create an instance of OrderAdjustment
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.OrderAdjustment createOrderAdjustment()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.OrderAdjustmentImpl();
    }

    /**
     * Create an instance of Money
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.Money createMoney()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.MoneyImpl();
    }

    /**
     * Create an instance of ResultMerchantCodeResultsTypeCouponResult
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.Result.MerchantCodeResultsType.CouponResult createResultMerchantCodeResultsTypeCouponResult()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.ResultImpl.MerchantCodeResultsTypeImpl.CouponResultImpl();
    }

    /**
     * Create an instance of AddMerchantOrderNumberElement
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.AddMerchantOrderNumberElement createAddMerchantOrderNumberElement()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.AddMerchantOrderNumberElementImpl();
    }

    /**
     * Create an instance of AddTrackingDataElement
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.AddTrackingDataElement createAddTrackingDataElement()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.AddTrackingDataElementImpl();
    }

    /**
     * Create an instance of DefaultTaxTable
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.DefaultTaxTable createDefaultTaxTable()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.DefaultTaxTableImpl();
    }

    /**
     * Create an instance of Calculate
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.Calculate createCalculate()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.CalculateImpl();
    }

    /**
     * Create an instance of NotificationAcknowledgment
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.NotificationAcknowledgment createNotificationAcknowledgment()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.NotificationAcknowledgmentImpl();
    }

    /**
     * Create an instance of NotificationAcknowledgmentElement
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.NotificationAcknowledgmentElement createNotificationAcknowledgmentElement()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.NotificationAcknowledgmentElementImpl();
    }

    /**
     * Create an instance of BuyerMarketingPreferencesElement
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.BuyerMarketingPreferencesElement createBuyerMarketingPreferencesElement()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.BuyerMarketingPreferencesElementImpl();
    }

    /**
     * Create an instance of MerchantCheckoutFlowSupportShippingMethodsTypeFlatRateShipping
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.MerchantCheckoutFlowSupport.ShippingMethodsType.FlatRateShipping createMerchantCheckoutFlowSupportShippingMethodsTypeFlatRateShipping()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.MerchantCheckoutFlowSupportImpl.ShippingMethodsTypeImpl.FlatRateShippingImpl();
    }

    /**
     * Create an instance of UnarchiveOrderElement
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.UnarchiveOrderElement createUnarchiveOrderElement()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.UnarchiveOrderElementImpl();
    }

    /**
     * Create an instance of ChargeOrderRequest
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.ChargeOrderRequest createChargeOrderRequest()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.ChargeOrderRequestImpl();
    }

    /**
     * Create an instance of AlternateTaxRuleTaxAreaType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.AlternateTaxRule.TaxAreaType createAlternateTaxRuleTaxAreaType()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.AlternateTaxRuleImpl.TaxAreaTypeImpl();
    }

    /**
     * Create an instance of Hello
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.Hello createHello()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.HelloImpl();
    }

    /**
     * Create an instance of DemoFailureElement
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.DemoFailureElement createDemoFailureElement()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.DemoFailureElementImpl();
    }

    /**
     * Create an instance of ShippingRestrictionsAllowedAreasTypeUsCountryArea
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.ShippingRestrictions.AllowedAreasType.UsCountryArea createShippingRestrictionsAllowedAreasTypeUsCountryArea()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.ShippingRestrictionsImpl.AllowedAreasTypeImpl.UsCountryAreaImpl();
    }

    /**
     * Create an instance of ArchiveOrderElement
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.ArchiveOrderElement createArchiveOrderElement()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.ArchiveOrderElementImpl();
    }

    /**
     * Create an instance of CheckoutRedirect
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.CheckoutRedirect createCheckoutRedirect()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.CheckoutRedirectImpl();
    }

    /**
     * Create an instance of AnonymousAddress
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.AnonymousAddress createAnonymousAddress()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.AnonymousAddressImpl();
    }

    /**
     * Create an instance of CancelOrderRequest
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.CancelOrderRequest createCancelOrderRequest()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.CancelOrderRequestImpl();
    }

    /**
     * Create an instance of GiftCertificateResult
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.GiftCertificateResult createGiftCertificateResult()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.GiftCertificateResultImpl();
    }

    /**
     * Create an instance of NewOrderNotificationElement
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.NewOrderNotificationElement createNewOrderNotificationElement()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.NewOrderNotificationElementImpl();
    }

    /**
     * Create an instance of MerchantCalculationCallback
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.MerchantCalculationCallback createMerchantCalculationCallback()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.MerchantCalculationCallbackImpl();
    }

    /**
     * Create an instance of Method
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.Method createMethod()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.MethodImpl();
    }

    /**
     * Create an instance of OrderAdjustmentMerchantCodesTypeCouponAdjustment
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.OrderAdjustment.MerchantCodesType.CouponAdjustment createOrderAdjustmentMerchantCodesTypeCouponAdjustment()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.OrderAdjustmentImpl.MerchantCodesTypeImpl.CouponAdjustmentImpl();
    }

    /**
     * Create an instance of ShippingRestrictionsExcludedAreasTypeUsCountryArea
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.ShippingRestrictions.ExcludedAreasType.UsCountryArea createShippingRestrictionsExcludedAreasTypeUsCountryArea()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.ShippingRestrictionsImpl.ExcludedAreasTypeImpl.UsCountryAreaImpl();
    }

    /**
     * Create an instance of MerchantCheckoutFlowSupportShippingMethodsTypePickup
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.MerchantCheckoutFlowSupport.ShippingMethodsType.Pickup createMerchantCheckoutFlowSupportShippingMethodsTypePickup()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.MerchantCheckoutFlowSupportImpl.ShippingMethodsTypeImpl.PickupImpl();
    }

    /**
     * Create an instance of CalculateMerchantCodeStringsType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.Calculate.MerchantCodeStringsType createCalculateMerchantCodeStringsType()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.CalculateImpl.MerchantCodeStringsTypeImpl();
    }

    /**
     * Create an instance of MerchantCalculatedShippingAdjustment
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.MerchantCalculatedShippingAdjustment createMerchantCalculatedShippingAdjustment()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.MerchantCalculatedShippingAdjustmentImpl();
    }

    /**
     * Create an instance of Address
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.Address createAddress()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.AddressImpl();
    }

    /**
     * Create an instance of Result
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.Result createResult()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.ResultImpl();
    }

    /**
     * Create an instance of CalculateAddressesType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.Calculate.AddressesType createCalculateAddressesType()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.CalculateImpl.AddressesTypeImpl();
    }

    /**
     * Create an instance of ArchiveOrderRequest
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.ArchiveOrderRequest createArchiveOrderRequest()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.ArchiveOrderRequestImpl();
    }

    /**
     * Create an instance of MerchantCalculationResults
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.MerchantCalculationResults createMerchantCalculationResults()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.MerchantCalculationResultsImpl();
    }

    /**
     * Create an instance of RefundOrderRequest
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.RefundOrderRequest createRefundOrderRequest()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.RefundOrderRequestImpl();
    }

    /**
     * Create an instance of ShoppingCartItemsType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.ShoppingCart.ItemsType createShoppingCartItemsType()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.ShoppingCartImpl.ItemsTypeImpl();
    }

    /**
     * Create an instance of ShippingRestrictionsAllowedAreasTypeUsStateArea
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.ShippingRestrictions.AllowedAreasType.UsStateArea createShippingRestrictionsAllowedAreasTypeUsStateArea()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.ShippingRestrictionsImpl.AllowedAreasTypeImpl.UsStateAreaImpl();
    }

    /**
     * Create an instance of RefundAmountNotificationElement
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.RefundAmountNotificationElement createRefundAmountNotificationElement()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.RefundAmountNotificationElementImpl();
    }

    /**
     * Create an instance of CouponResult
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.CouponResult createCouponResult()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.CouponResultImpl();
    }

    /**
     * Create an instance of DiagnoseResponse
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.DiagnoseResponse createDiagnoseResponse()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.DiagnoseResponseImpl();
    }

    /**
     * Create an instance of MerchantCodeString
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.MerchantCodeString createMerchantCodeString()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.MerchantCodeStringImpl();
    }

    /**
     * Create an instance of FlatRateShippingAdjustment
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.FlatRateShippingAdjustment createFlatRateShippingAdjustment()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.FlatRateShippingAdjustmentImpl();
    }

    /**
     * Create an instance of ResultMerchantCodeResultsType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.Result.MerchantCodeResultsType createResultMerchantCodeResultsType()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.ResultImpl.MerchantCodeResultsTypeImpl();
    }

    /**
     * Create an instance of ChargeOrderElement
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.ChargeOrderElement createChargeOrderElement()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.ChargeOrderElementImpl();
    }

    /**
     * Create an instance of ShippingRestrictionsExcludedAreasType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.ShippingRestrictions.ExcludedAreasType createShippingRestrictionsExcludedAreasType()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.ShippingRestrictionsImpl.ExcludedAreasTypeImpl();
    }

    /**
     * Create an instance of SendBuyerMessageRequest
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.SendBuyerMessageRequest createSendBuyerMessageRequest()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.SendBuyerMessageRequestImpl();
    }

    /**
     * Create an instance of ProcessOrderRequest
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.ProcessOrderRequest createProcessOrderRequest()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.ProcessOrderRequestImpl();
    }

    /**
     * Create an instance of UnarchiveOrderRequest
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.UnarchiveOrderRequest createUnarchiveOrderRequest()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.UnarchiveOrderRequestImpl();
    }

    /**
     * Create an instance of MerchantCheckoutFlowSupportShippingMethodsTypeMerchantCalculatedShipping
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.MerchantCheckoutFlowSupport.ShippingMethodsType.MerchantCalculatedShipping createMerchantCheckoutFlowSupportShippingMethodsTypeMerchantCalculatedShipping()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.MerchantCheckoutFlowSupportImpl.ShippingMethodsTypeImpl.MerchantCalculatedShippingImpl();
    }

    /**
     * Create an instance of ShoppingCart
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.ShoppingCart createShoppingCart()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.ShoppingCartImpl();
    }

    /**
     * Create an instance of RequestReceivedResponse
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.RequestReceivedResponse createRequestReceivedResponse()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.RequestReceivedResponseImpl();
    }

    /**
     * Create an instance of ByeElement
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.ByeElement createByeElement()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.ByeElementImpl();
    }

    /**
     * Create an instance of ShippingRestrictions
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.ShippingRestrictions createShippingRestrictions()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.ShippingRestrictionsImpl();
    }

    /**
     * Create an instance of ShippingRestrictionsAllowedAreasTypeUsZipArea
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.ShippingRestrictions.AllowedAreasType.UsZipArea createShippingRestrictionsAllowedAreasTypeUsZipArea()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.ShippingRestrictionsImpl.AllowedAreasTypeImpl.UsZipAreaImpl();
    }

    /**
     * Create an instance of OrderStateChangeNotification
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.OrderStateChangeNotification createOrderStateChangeNotification()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.OrderStateChangeNotificationImpl();
    }

    /**
     * Create an instance of USStateArea
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.USStateArea createUSStateArea()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.USStateAreaImpl();
    }

    /**
     * Create an instance of MerchantCalculations
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.MerchantCalculations createMerchantCalculations()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.MerchantCalculationsImpl();
    }

    /**
     * Create an instance of RefundOrderElement
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.RefundOrderElement createRefundOrderElement()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.RefundOrderElementImpl();
    }

    /**
     * Create an instance of AddMerchantOrderNumberRequest
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.AddMerchantOrderNumberRequest createAddMerchantOrderNumberRequest()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.AddMerchantOrderNumberRequestImpl();
    }

    /**
     * Create an instance of DeliverOrderRequest
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.DeliverOrderRequest createDeliverOrderRequest()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.DeliverOrderRequestImpl();
    }

    /**
     * Create an instance of Bye
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.Bye createBye()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.ByeImpl();
    }

    /**
     * Create an instance of ErrorResponseWarningMessagesType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.ErrorResponse.WarningMessagesType createErrorResponseWarningMessagesType()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.ErrorResponseImpl.WarningMessagesTypeImpl();
    }

    /**
     * Create an instance of OrderAdjustmentMerchantCodesTypeGiftCertificateAdjustment
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.OrderAdjustment.MerchantCodesType.GiftCertificateAdjustment createOrderAdjustmentMerchantCodesTypeGiftCertificateAdjustment()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.OrderAdjustmentImpl.MerchantCodesTypeImpl.GiftCertificateAdjustmentImpl();
    }

    /**
     * Create an instance of CheckoutShoppingCart
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.CheckoutShoppingCart createCheckoutShoppingCart()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.CheckoutShoppingCartImpl();
    }

    /**
     * Create an instance of ShippingRestrictionsAllowedAreasType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.ShippingRestrictions.AllowedAreasType createShippingRestrictionsAllowedAreasType()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.ShippingRestrictionsImpl.AllowedAreasTypeImpl();
    }

    /**
     * Create an instance of ErrorResponse
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.ErrorResponse createErrorResponse()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.ErrorResponseImpl();
    }

    /**
     * Create an instance of TaxTablesAlternateTaxTablesType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.TaxTables.AlternateTaxTablesType createTaxTablesAlternateTaxTablesType()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.TaxTablesImpl.AlternateTaxTablesTypeImpl();
    }

    /**
     * Create an instance of PickupShippingAdjustment
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.PickupShippingAdjustment createPickupShippingAdjustment()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.PickupShippingAdjustmentImpl();
    }

    /**
     * Create an instance of DefaultTaxRule
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.DefaultTaxRule createDefaultTaxRule()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.DefaultTaxRuleImpl();
    }

    /**
     * Create an instance of MerchantCalculatedShipping
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.MerchantCalculatedShipping createMerchantCalculatedShipping()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.MerchantCalculatedShippingImpl();
    }

    /**
     * Create an instance of OrderAdjustmentMerchantCodesType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.OrderAdjustment.MerchantCodesType createOrderAdjustmentMerchantCodesType()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.OrderAdjustmentImpl.MerchantCodesTypeImpl();
    }

    /**
     * Create an instance of USZipArea
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.USZipArea createUSZipArea()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.USZipAreaImpl();
    }

    /**
     * Create an instance of TrackingData
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.TrackingData createTrackingData()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.TrackingDataImpl();
    }

    /**
     * Create an instance of CartExpiration
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.CartExpiration createCartExpiration()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.CartExpirationImpl();
    }

    /**
     * Create an instance of AnyType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.AnyType createAnyType()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.AnyTypeImpl();
    }

    /**
     * Create an instance of DiagnoseResponseWarningsType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.DiagnoseResponse.WarningsType createDiagnoseResponseWarningsType()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.DiagnoseResponseImpl.WarningsTypeImpl();
    }

    /**
     * Create an instance of Pickup
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.Pickup createPickup()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.PickupImpl();
    }

    /**
     * Create an instance of CalculateShippingType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.Calculate.ShippingType createCalculateShippingType()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.CalculateImpl.ShippingTypeImpl();
    }

    /**
     * Create an instance of CheckoutShoppingCartElement
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.CheckoutShoppingCartElement createCheckoutShoppingCartElement()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.CheckoutShoppingCartElementImpl();
    }

    /**
     * Create an instance of DefaultTaxTableTaxRulesType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.DefaultTaxTable.TaxRulesType createDefaultTaxTableTaxRulesType()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.DefaultTaxTableImpl.TaxRulesTypeImpl();
    }

    /**
     * Create an instance of BuyerMarketingPreferences
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.BuyerMarketingPreferences createBuyerMarketingPreferences()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.BuyerMarketingPreferencesImpl();
    }

    /**
     * Create an instance of DemoFailure
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.DemoFailure createDemoFailure()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.DemoFailureImpl();
    }

    /**
     * Create an instance of CouponAdjustment
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.CouponAdjustment createCouponAdjustment()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.CouponAdjustmentImpl();
    }

    /**
     * Create an instance of DeliverOrderElement
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.DeliverOrderElement createDeliverOrderElement()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.DeliverOrderElementImpl();
    }

    /**
     * Create an instance of MerchantCalculationCallbackElement
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.MerchantCalculationCallbackElement createMerchantCalculationCallbackElement()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.MerchantCalculationCallbackElementImpl();
    }

    /**
     * Create an instance of AlternateTaxTableAlternateTaxRulesType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.AlternateTaxTable.AlternateTaxRulesType createAlternateTaxTableAlternateTaxRulesType()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.AlternateTaxTableImpl.AlternateTaxRulesTypeImpl();
    }

    /**
     * Create an instance of RiskInformationNotificationElement
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.google.checkout.schema._2.RiskInformationNotificationElement createRiskInformationNotificationElement()
        throws javax.xml.bind.JAXBException
    {
        return new com.google.checkout.schema._2.impl.RiskInformationNotificationElementImpl();
    }

}
